export const LOGIN = "LOGIN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//STUDENTS
export const SET_ALL_STUDENTS = "SET_ALL_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const SET_STUDENT = "SET_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";

//TEACHERS
export const SET_ALL_TEACHERS = "SET_ALL_TEACHERS";
